
#-----------------------------------------------------------------------
APP       := Center
TARGET    := TestClient
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   +=

#-----------------------------------------------------------------------
include /home/tarsproto/Center/EFServer/EFServer.mk
include /works/evn_tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
