
#-----------------------------------------------------------------------

APP       := Center
TARGET    := ProxyServer
CONFIG    := ./config.conf
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------
include /home/tarsproto/Center/EFServer/EFServer.mk
include /works/evn_tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
