// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.1.0.
// **********************************************************************

#ifndef __COMMON_H_
#define __COMMON_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
using namespace std;


namespace Center
{
    const tars::Int32 SUCCESS = 0;

    const tars::Int32 LINK_BROKEN = -1001;

    const tars::Int32 REPEAT_LOGIN = -1002;

    const tars::Int32 ACK_TIMEOUT = -1003;

    const tars::Int32 ORDER_UNFINISHED = -1004;

    const tars::Int32 PARAM_LENGTH_ERROR = -1005;

    const tars::Int32 UNKNOWN_ERROR = -1999;

    const tars::Int32 REQT_SEND_FAILED = -2001;

    const tars::Int32 REQT_QUEUESIZE_OVERLIMIT = -2002;

    const tars::Int32 REQT_RATEPERSEC_OVERLIMIT = -2003;


}



#endif
