
#-----------------------------------------------------------------------

APP       := Center
TARGET    := EFServer
CONFIG    := ./lib/libthosttraderapi.so ./config.conf
STRIP_FLAG:= N
TARS2CPP_FLAG:=

INCLUDE   +=
LIB       += -L./lib -lthosttraderapi -Wl,-R .

#-----------------------------------------------------------------------

include /works/evn_tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
